### ISSUE TITLE
[BUG] Crosshair does not stay centered during gameplay

### ISSUE THREAD

**Issue by naginatairl** [apex-legends-bugs/apex-legends-bugs#58]
**Describe the bug**
After firing a weapon, the crosshair will drift away from the center of the screen. It disorients your aim and makes the crosshair unreliable in fights.

**To Reproduce**
1. Fire any weapon in hipfire.
2. The crosshair will go off center for a short period of time during and after firing.

**Expected behavior**
The crosshair remains perfectly centered at all times.

**Why could this be happening?**
Apex reuses old code from the Titanfall games, such as this. It is likely that the bug was never patched during the engine's lifespan.

**Clips and Screenshots**
A wrthcrw video explains this: https://www.youtube.com/watch?v=qOl6WcZAoZs

**System (please complete the following information):**
 - Platform: any
 - When exactly the issue happened (exact day and date): any time

**Additional context**
N/A

**Workarounds**
On Windows PC, third-party overlay programs can create a perfectly centered crosshair, such as ReShade. This solution is unavailable to Steam Deck, Linux PC, and console players, so they must use a crosshair overlay on their monitor or draw a dot on the center of it.

**Comment by apex-legends-bugs** [comment]
Thank you for taking the time to report this. While this creates additional difficulty in aiming, I have seen a developer mention at some point that this is intended, in order to heighten the skill ceiling in gun play.

Other games do this as well and they use completely different engines. For example, see Valorant.

https://www.youtube.com/shorts/7cND3_021Jg

Right at the beginning of the video, when the player jumps off the zipline, the crosshair can be seen floating way to the left. This is called movement sway. Similarly, when you spam fire a gun, that's called aim drift.

This sort of mechanic exists in games in order to make movement and repeat shooting a tradeoff vs accuracy and is meant as inherent difficulty.

To give a simple example of intended difficulty, games also have walls for enemies to hide behind and surprise you.

The crosshair moving around on the screen is actually meant to _help you_. For example, CS is a game where the crosshair always stays centered in the middle of the screen.

https://www.youtube.com/watch?v=mpSigKlgeLc

Notice how the crosshair is always dead center on the screen, but the gun just shoots where ever. You have to learn these patterns and you have to learn that you have to end up aiming at someone's feet to hit their head.

So in CS, the place the gun will shoot and the crosshair are actually two separate positions which are unrelated.

With Apex, the crosshair follows the position of where the gun will hit. You just have to keep moving the crosshair so that it's over your target, and your gun will hit it.

This is similar to MW2 and 3 (start watching about 3 minutes 15 seconds in): https://youtu.be/YMeIQWphLJ0?t=195

So there's a couple things here:

1. the place where your gun will actually shoot moves around on the screen. This is intended difficulty. If you didn't have that, every gun would be a laser and there would be no skill in aiming or recoil control.
2. the place where your crosshair is follows 1 around on the screen. This is intended to make things easier for you.

Crosshair overlays like with reshade are actually wrong and they remove the advantage you get with 2.

I'm going to label this as an intended feature and close this, but if you have good arguments why this behavior is bugged, I'll be happy to re-open this! Let me know what you think.

Again thanks for reporting and have a nice day.
